 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/analises", type: :request do
  
  # Analise. As you add validations to Analise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Analise.create! valid_attributes
      get analises_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      analise = Analise.create! valid_attributes
      get analise_url(analise)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_analise_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      analise = Analise.create! valid_attributes
      get edit_analise_url(analise)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Analise" do
        expect {
          post analises_url, params: { analise: valid_attributes }
        }.to change(Analise, :count).by(1)
      end

      it "redirects to the created analise" do
        post analises_url, params: { analise: valid_attributes }
        expect(response).to redirect_to(analise_url(Analise.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Analise" do
        expect {
          post analises_url, params: { analise: invalid_attributes }
        }.to change(Analise, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post analises_url, params: { analise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested analise" do
        analise = Analise.create! valid_attributes
        patch analise_url(analise), params: { analise: new_attributes }
        analise.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the analise" do
        analise = Analise.create! valid_attributes
        patch analise_url(analise), params: { analise: new_attributes }
        analise.reload
        expect(response).to redirect_to(analise_url(analise))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        analise = Analise.create! valid_attributes
        patch analise_url(analise), params: { analise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested analise" do
      analise = Analise.create! valid_attributes
      expect {
        delete analise_url(analise)
      }.to change(Analise, :count).by(-1)
    end

    it "redirects to the analises list" do
      analise = Analise.create! valid_attributes
      delete analise_url(analise)
      expect(response).to redirect_to(analises_url)
    end
  end
end
